routes/web.php
<?php

use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'articles'], function () {
    Route::get('/', 'ArticleController@categories')->name('article.categories');
    Route::get('{category}/{article}', 'ArticleController@show')->name('article.article');
});

Route::group(['prefix' => 'salons'], function () {
    Route::get('/', 'SalonController@index')->name('salon.index');
    Route::get('{salon}', 'SalonController@view')->name('salon.view');
    Route::post('/record', 'SalonController@record')->name('salon.service.record');
});

Route::group(['prefix' => 'services', 'as' => 'service-category.'], function () {
    Route::get('{serviceCategory}', 'ServiceCategoryController@show')->name('show');
    Route::get('{serviceCategory}/{service}', 'ServiceCategoryController@service')->name('service');
});

Route::group(['prefix' => 'search'], function () {
    Route::get('/', 'SearchController@index')->name('search.index');
});

Route::group(['prefix' => 'shop'], function () {
    Route::get('/', 'CatalogController@index')->name('catalog.index');
    Route::get('/new', 'CatalogController@new')->name('catalog.new');
    Route::get('/popular', 'CatalogController@popular')->name('catalog.popular');
    Route::get('/sale', 'CatalogController@sale')->name('catalog.sale');
    Route::get('/{category}', 'CatalogController@category')->name('category');
    Route::get('/{category}/{product}/', 'CatalogController@product')->name('product');
});

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/delete/{id}', 'CartController@delete')->name('cart.delete');
Route::get('/cart/add/{id}', 'CartController@add')->name('cart.add');
Route::post('/cart/update', 'CartController@update')->name('cart.update');

Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
Route::post('/checkout', 'CheckoutController@post')->name('checkout.post');
Route::get('/checkout/{order}.pdf', 'CheckoutController@pdf')->name('checkout.pdf')->middleware(['signed'])->where('order', '[0-9]+');
Route::get('/checkout/{order}/mail', 'CheckoutController@mail')->name('checkout.mail')->middleware(['signed'])->where('order', '[0-9]+');
Route::get('/checkout/{order}', 'CheckoutController@view')->name('checkout.view')->middleware(['signed'])->where('order', '[0-9]+');
Route::post('/checkout/delivery-update', 'CheckoutController@updateDelivery')->name('checkout.deliveryUpdate');

Route::post('/record', 'CatalogController@createRecord')->name('product.store');

Route::get('/contacts', 'ContactController@index')->name('contact');

Route::post('/contacts', 'ContactController@store')->name('contact.store');

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::get('gallery', 'PortfolioController@index')->name('portfolio.index');

Route::group(['prefix' => 'customer'], function () {
    Route::group(['namespace' => 'Customer'], function() {
        Route::get('/', 'HomeController@index')->name('customer.dashboard');
        Route::get('/orders', 'HomeController@orders')->name('customer.orders');

        // Login
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('customer.login');
        Route::post('login', 'Auth\LoginController@login');
        Route::post('logout', 'Auth\LoginController@logout')->name('customer.logout');

        // Register
        Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('customer.register');
        Route::post('register', 'Auth\RegisterController@register');

        // Passwords
        Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('customer.password.email');
        Route::post('password/reset', 'Auth\ResetPasswordController@reset');
        Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('customer.password.request');
        Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('customer.password.reset');

        // Must verify email
        Route::get('email/resend','Auth\VerificationController@resend')->name('customer.verification.resend');
        Route::get('email/verify','Auth\VerificationController@show')->name('customer.verification.notice');
        Route::get('email/verify/{id}/{hash}','Auth\VerificationController@verify')->name('customer.verification.verify');

        Route::post('address', 'HomeController@storeAddress')->name('customer.storeAddress');
        Route::post('update', 'HomeController@store')->name('customer.storeAddress');
    });
});

Route::get('{path}', 'RoutableController@show')->where('path', '[a-zA-Z0-9\-/_]+');

// just for sake of url generation

Route::get('{category}', 'ArticleController@category')->name('article.articles');
Route::get('{slug}', [
    'uses' => 'PageController@getPage'
])->where('slug', '([A-Za-z0-9\-\/]+)')->name('pages');

app/Http/Controllers/ServiceCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Salon\SalonService;
use App\Models\Salon\SalonServiceCategory;

class ServiceCategoryController extends Controller
{
    public function show(SalonServiceCategory $serviceCategory)
    {
        $services = $serviceCategory->salonServices;
        $salons = $serviceCategory->salons;

        return view('service-categories.show', compact('serviceCategory','services', 'salons'));
    }

    public function service(SalonServiceCategory $serviceCategory, SalonService $service)
    {
        return view('service-categories.service', compact('serviceCategory', 'service'));
    }
}

resources/views/service-categories/service.blade.php
@extends('layouts.app', [
    'title' => $service->title
])

@section('breadcrumbs')
    <div id="hb-innerbanner" class="hb-innerbanner hb-haslayout">
        <div class="containers">
            <div class="hb-innerbanner-area">
                <div class="hb-bannarheading">
                    <h3 style="color: white;">{{ $service->title }}</h3>
                </div>
                <ul class="hb-breadcrumb">
                    <li><a href="{{ route('home') }}">Главная</a></li>
                    <li><a href="{{ route('salon.index') }}">Салоны</a></li>
                    <li><a href="{{ route('salon.view', [$service->salons->first()]) }}">{{ $service->salons->first()->title }}</a></li>
                    <li><a href="{{ route('service-category.show', [$serviceCategory]) }}">{{ $serviceCategory->title }}</a></li>
                    <li>{{ $service->title }}</li>
                </ul>
            </div>
        </div>
    </div>
@endsection

@section('content')
    <section id="hb-blog" class="hb-blog hb-sectionspace hb-haslayout service">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="hb-post-area hb-blogdetails">
                        <article class="hb-post">
                            <div class="hb-postcontent">
                                <h1>{{ $service->title }}</h1>
                            </div>
                            <figure class="hb-postimage">
                                <img src="/storage/{{$service->image}}" alt="image description" style="width: 330px;">
                            </figure>
                            <div class="hb-description">
                                {!! $service->description !!}
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </div>
    </section>
        <script type="text/javascript" src="https://w309180.yclients.com/widgetJS" charset="UTF-8"></script>
@endsection

resources/views/service-categories/show.blade.php
@extends('layouts.app', [
    'title' => $serviceCategory->title
])

@section('breadcrumbs')
    <div id="hb-innerbanner" class="hb-innerbanner hb-haslayout">
        <div class="containers">
            <div class="hb-innerbanner-area">
                <div class="hb-bannarheading">
                    <h3 style="color: white;">{{ $serviceCategory->title }}</h3>
                </div>
                <ul class="hb-breadcrumb">
                    <li><a href="{{ route('home') }}">Главная</a></li>
                    <li>{{ $serviceCategory->title }}</li>
                </ul>
            </div>
        </div>
    </div>
        <script type="text/javascript" src="https://w309180.yclients.com/widgetJS" charset="UTF-8"></script>
@endsection


@section('content')
    <section id="hb-services" class="hb-services v2 hb-bg hb-haslayout hb-sectionspace">
        @if ($errors->any())
            <div class="container">
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        <div class="container">
            <div class="row">
                <div class=" col-xs-12 col-sm-12 col-sm-offset-0 col-md-8 col-md-offset-2">
                    <div class="hb-sectionhead">
                        <div class="hb-sectiontitle">
                            <h2><span>Mon Platin Center</span>
                                {{ $serviceCategory->title }}
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="hb-post-area">
                    @foreach($salons as $salon)
                        <div class="row mt-50">
                            <div class="col-xs-12">
                                <h3 class="text-center">
                                    <span>{{ $salon->title }}</span>
                                </h3>
                            </div>

                            @foreach($salon->salonServices->where('salon_service_category_id', $serviceCategory->id) as $service)
                                <div class="col-xs-12 col-sm-6 col-md-3 mt-40">
                                    <div class="hb-servicebox">
                                        <div class="hb-servicecontentprice"  style="min-height: 285px">
                                            <figure class="hb-serviceprice">
                                                <h2>{{ $service->price }} р.</h2>
                                            </figure>
                                            <h3 class="hb-headingtree">
                                                <a href="{{ route('service-category.service', [$serviceCategory, $service]) }}">
                                                    {{ $service->title }}
                                                </a>
                                            </h3>
                                            <a
                                                href="#"
                                                data-modal="#modal-service-{{$service->id}}"
                                                class="hb-btn modal__trigger"
                                            >
                                                Записаться
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </section>

    @if (!empty($serviceCategory->description))
        <section id="hb-blog" class="hb-blog hb-haslayout service">
            <div class="container">
                <div class="row">
                    <div class=" col-xs-12 col-sm-12 col-sm-offset-0 col-md-8 col-md-offset-2">
                        <div class="hb-sectionhead mt-50">
                            <div class="hb-sectiontitle">
                                <h2><span>Mon Platin Center</span>
                                    Об услуге
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="hb-post-area hb-blogdetails">
                            <article class="hb-post">
                                <div class="hb-description">
                                    {!! $serviceCategory->description !!}
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    @endif

    @foreach($services as $service)
        <div id="modal-service-{{ $service->id }}" class="modal modal__bg" role="dialog" aria-hidden="true">
            <div class="modal__dialog">
                <div class="modal__content">
                    <h2 style="padding: 20px; text-align: center">{{ $service->title }}</h2>
                    <form
                        class="row form-contact contact_form"
                        action="{{ route('salon.service.record') }}"
                        method="post"
                        id="contactFormService{{ $service->id }}"
                    >
                        @csrf
                        <div class="col-sm-12">
                            <div class="form-group">
                                Введите Ваше имя
                                <input
                                    class="form-control"
                                    name="name"
                                    id="name"
                                    type="text"
                                    placeholder="Имя"
                                    required
                                >
                            </div>
                            <div class="form-group">
                                Введите Ваш номер
                                <input
                                    required
                                    class="form-control"
                                    name="phone"
                                    id="number"
                                    type="text"
                                    placeholder="+375-(XX)-XXX-XX-XX"
                                >
                            </div>
                            <div class="form-group hidden">
                                Введите Ваш номер
                                <input
                                    required
                                    hidden
                                    class="form-control"
                                    value="{{ $service->id }}"
                                    name="service_id"
                                    id="serivce_id"
                                    type="text"
                                >
                            </div>
                            <div class="form-group">
                                Выберите салон
                                <select
                                    required
                                    class="form-control"
                                    name="service_salon"
                                    id="service_salon"
                                >
                                    @foreach($service->salons as $salon)
                                        <option value="{{ $salon->id }}">{{ $salon->title }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group mt-lg-3">
                                <button style="cursor: pointer;" onclick="form_submitService{{ $service->id }}()"
                                        type="submit" class="hb-btn button-contactFormСontact">Отправить заявку
                                </button>
                            </div>
                        </div>
                    </form>
                    <!-- modal close button -->
                    <a href="" class="modal__close demo-close">
                        <svg class="" viewBox="0 0 24 24">
                            <path
                                d="M19 6.41l-1.41-1.41-5.59 5.59-5.59-5.59-1.41 1.41 5.59 5.59-5.59 5.59 1.41 1.41 5.59-5.59 5.59 5.59 1.41-1.41-5.59-5.59z"/>
                            <path d="M0 0h24v24h-24z" fill="none"/>
                        </svg>
                    </a>

                </div>
            </div>
        </div>

        <script type="text/javascript">
            function form_submitService{{ $service->id }}() {
                document.getElementById("contactFormService{{ $service->id }}").submit();
            }
        </script>
    @endforeach
@endsection